spring:
  datasource:
    url: jdbc:sqlserver://veterinariaupc.database.windows.net:1433;database=veterinariadb;user=u201710092@veterinariaupc;password=Kjkszpj1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
